spring:
  application:
    name: spring-boot-h2-jpa
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
    url: jdbc:h2:mem:test
    platform: h2
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      max-lifetime: 1830000
      maximum-pool-size: 10
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: h2
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  h2:
    console:
      path: /h2-console
      enabled: true
# spring.h2.console.settings.web-allow-others=true //设置为true，h2 web consloe就可以在远程访问了。否则只能在本机访问。
# spring.h2.console.enabled=true                   //设置为true，程序开启时就会启动h2 web console(默认是false) 访问URL是 http://localhost:8080/h2-console

info:
  app:
    name: ${spring.application.name}
    version: V1.0.0
    time: 2020年03月17日 12:00:00
  describe: 项目描述
  home: /
  author: administrator
  licensed: MIT Licensed